# Pipeline DevSecOps - Laboratorio Final curso DevSecOps
# Inicio del Pipeline

name: Pipeline DevSecOps - Laboratorio Final

on:
  push:
    branches:
      - feature/pipeline-devsecops

jobs:
  security-pipeline:
    name: Pipeline de Seguridad
    runs-on: ubuntu-latest
    
    steps:
      # ETAPA 1: Clonación del repositorio
      - name: 1. Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # ETAPA 2: Análisis SAST con SonarCloud
      - name: 2. SonarCloud Scan (SAST)
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
